In [5]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
!pip install update numpy


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
# 배열의 구조
arr.shape # 1차원 배열, 크기 4

(4,)

In [11]:
# 2차원 배열
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
# arr2 구조
arr2.shape # 2차원 배열, 2행 4열

(2, 4)

In [16]:
arr3 = np.array([[1,2,3,4]])
arr3.shape

(1, 4)

In [18]:
arr4 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],
                 [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]])
arr4.shape

(2, 4, 4)

In [19]:
# 넘파이 데이터타입 확인
arr3.dtype

dtype('int64')

- 넘파이 자료형
    - 부호 정수 : int8, int16, int32, int6
    - 무부호 정소 : uint8, uint16, uint32, uint64
    - 실수 : float8, float16, float32, float64
    - 복소수 : complex8, complex16, complex32, complex64
    - 문자열 : string_
    - 불린 : bool
    - 유니코드 : unicode_
    - 파이썬오브젝트 : object

- 넘파이 배열 정의

In [20]:
# 1차원 요소 10개가 모두 0인 배열 초기화
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
# 2차원 2행 4열 모두가 0인 배열 초기화
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
# 1차원 요소 10개를 모두 1로 배열 초기화
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
# 2차원 배열, 2행 4열 모두가 1로 초기화
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
# 3부터 1씩 증가, 9가 마지막인 배열 초기화
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [28]:
# 3부터 2씩 증가, 9가 마지막인 배열 초기화
np.arange(3, 10, 2)

array([3, 5, 7, 9])

- 사용하는 이유

In [30]:
## 대량리스트 생성
pyList = list(range(100_000_000))
npList = np.arange(100_000_000)

: 

In [ ]:
pyList